In [17]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [18]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [19]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv('../landing/' + arquivo, sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10003    PREGO  BT10    100    660  z0019_2.csv 2026-02-22 11:52:40.401086
1  10004    SERRA  BT20    100    200  z0019_2.csv 2026-02-22 11:52:40.401086
2  10005  MACHADO  BT30    100    300  z0019_2.csv 2026-02-22 11:52:40.401086

In [20]:
con.execute("""
CREATE TABLE IF NOT EXISTS bronze_produtos (
   NATBR VARCHAR,
   MAKTX VARCHAR,
   WERKS VARCHAR,  
   MAINS VARCHAR,
   LABST VARCHAR,
   nome_arquivo VARCHAR,
   data_ingestao TIMESTAMP
            
    
)
""")

In [21]:
con.execute("""INSERT INTO bronze_produtos SELECT * FROM df""")

In [27]:
resultado = con.execute("""SELECT * FROM bronze_z0019""").fetchdf()
resultado.head(20)

    NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0   10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-02-22 11:32:18.811185
1   10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-02-22 11:32:18.811185
2   10003     PREGO  BT10   100    50  z0019_1.csv 2026-02-22 11:32:18.811185
3   10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-02-22 11:32:18.811185
4   10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-02-22 11:32:18.811185
5   10003     PREGO  BT10   100    50  z0019_1.csv 2026-02-22 11:32:18.811185
6   10003     PREGO  BT10   100   660  z0019_2.csv 2026-02-22 11:51:13.117184
7   10004     SERRA  BT20   100   200  z0019_2.csv 2026-02-22 11:51:13.117184
8   10005   MACHADO  BT30   100   300  z0019_2.csv 2026-02-22 11:51:13.117184
9   10003     PREGO  BT10   100   660  z0019_2.csv 2026-02-22 11:52:40.401086
10  10004     SERRA  BT20   100   200  z0019_2.csv 2026-02-22 11:52:40.401086
11  10005   MACHADO  BT30   100   300  z0019_2.csv 2026-02-22 11:52:40.401086

In [25]:
con.execute("""ALTER TABLE bronze_produtos RENAME TO bronze_z0019""")

In [28]:
con.close()